# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'wowapowcomics'

google-ID: ''

menu:
- {name: 'Clearview', folder: 'pages', file: 'clearview.html'}
- {name: 'Country Cat BBQ', folder: 'pages', file: 'countrycatbbq.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'instagram', link: 'https://instagram.com/wowapowcomics'}
- {icon: 'envelope', link: 'mailto:contact@wowapowcomics.com'}
- {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Share a comic.'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Drawn on'
